### ISSUE TITLE
bug in degPlotWide() (v. 1.18.1) only works if group="group"

### ISSUE THREAD

**Issue by hexaflexa** [lpantano/DEGreport#25]
I think there is a bug in degPlotWide() in version 1.18.1 in the following code:

```
    if (is.null(group)) {
        dd$treatment = "one_group"
    }
    else {
        dd$treatment = dd[, "group"]
    }
```

With the above code, ```degPlotWide(dse, gene_names, group = "group")```
works because is it grouping by "group", but if you change it to any other metadata column, you get the error:

```Error in `[.data.frame`(dd, , "group") : undefined columns selected```

which is fixed either by changing: "group" to group in this line:
```
        dd$treatment = dd[, "group"]   # SHOULD BE group not "group"
```
I initially spotted this problem with my own DESeqDataSet which didn't have a "group" metadata column, but instead used "condition" or "treatment".  And then when I copied the condition column artificially to make a new metadata column called group, the plotting worked.

**Comment by lpantano** [comment]
Hi,

Thanks so much for posting the issue. There is actually a bug when the input is a SE or similar object. I fixed in development.

Thanks!

**Comment by hexaflexa** [comment]
Thanks for the quick reply!  I installed the latest version and it works as expected.
