### ISSUE TITLE
degPatterns error

### ISSUE THREAD

**Issue by wangmhan** [lpantano/DEGreport#27]
Hi,
I tried to use degPatterns with consensusCluster = TRUE, cannot get a result but end fraction message. Does anyone know how to fix it?
Thanks!

**Comment by lpantano** [comment]
Hi @wangmhan ,

Can you post the exact error you get? If you try the example in the man page, does it work? 

If you paste here all the output when you run it, I may able to see what is happening.

Thanks!

**Comment by wangmhan** [comment]
Hi,

I tried the example, it also cannot work with consensusCluster = TRUE.

The code is like this:
library("DEGreport")

data(humanGender)
library(SummarizedExperiment)
library(ggplot2)
ma <- assays(humanGender)[[1]][1:100,]
des <- colData(humanGender)
des[["other"]] <- sample(c("a", "b"), 85, replace = TRUE)
res <- degPatterns(ma, des, time="group", col = "other",consensusCluster = TRUE)

And the error report is:
Working with 100 genes.
end fraction
Error in frame() : figure margins too large

Did I misunderstand end fraction as error? But it cannot get the plot of cluster as usual.

**Comment by lpantano** [comment]
I see, are you using R studio, this happens in general when the Panel for figures is too small. Can you try to increase the size of that panel? It is working for me. 

If you are not using R studio, let me know.

Cheers

**Comment by wangmhan** [comment]
Hi,
yes I am using R studio. And you are right, after increasing the size of
panel, it works!
Thanks a lot!

Cheers

Lorena Pantano <notifications@github.com> 于2019年8月9日周五 下午9:49写道：

**Comment by FengWalker** [comment]
Hi,
I tried the example, 
The code is like this:

library("DEGreport")
data(humanGender)
library(SummarizedExperiment)
library(ggplot2)
ma <- assays(humanGender)[[1]][1:100,]
des <- colData(humanGender)
des[["other"]] <- sample(c("a", "b"), 85, replace = TRUE)
res <- degPatterns(ma, des, time="group", col = "other",consensusCluster = TRUE)

And the error report is:
Working with 100 genes.
Working with 63 genes after filtering: minc > 15
Joining, by = "merge"
error: Problem with `summarise()` input `n_genes`.
x could not find function "n"
i Input `n_genes` is `n()`.
i The error occurred in group 1: merge = "aFemale", cluster = 1, group = "Female", other = "a".
Run `rlang::last_error()` to see where the error occurred. 

and I ran rlang::last_error() with this result 

> rlang::last_error()
<error/dplyr_error>
Problem with `summarise()` input `n_genes`.
x could not find function "n"
i Input `n_genes` is `n()`.
i The error occurred in group 1: merge = "aFemale", cluster = 1, group = "Female", other = "a".
Backtrace:
  1. DEGreport::degPatterns(...)
  9. base::.handleSimpleError(...)
 10. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.

**Comment by lpantano** [comment]
Hi, Thanks for reporting this. 
Can you tell me the version of the package and R/Bioconductor you are using?

**Comment by FengWalker** [comment]
Thanks for your reply.
I run example in Rstudio Version 1.2.5033 and R version 4.0.3.  
My DEGreport  is version 1.25.3 and installed by  remotes .

remotes::install_github("lpantano/DEGreport")

All packages were updated during the installation.

**Comment by lpantano** [comment]
Hi,

I was able to reproduce when installing from github, I am trying to fix this.

Can you trying installation directly from Bioconductor:

`BiocManager::install("DEGreport")`

Thanks!
