### ISSUE TITLE
How is variance explained calculated for degCovariates?

### ISSUE THREAD

**Issue by Zepeng-Mu** [lpantano/DEGreport#31]
Hi, while using the function `degCovariates` I found that the proportion of variance explained in the output plot is very different from what I get from `summary(pca.res)`, where `pca.res` is the result from `prcomp` using default parameters.

Therefore I am wondering how is PCA done internally in the `degCovariates` function. Is it possible for me to get exact the same results from this function as `prcomp`?

Thanks

**Comment by lpantano** [comment]
Hi,

Thanks for the feedback, this is the line where the PCT is calculated:

https://github.com/lpantano/DEGreport/blob/master/R/covariate.R#L33

Let me know what do you think.

Cheers

**Comment by Zepeng-Mu** [comment]
This is exactly what I am looking for. Thanks
