### ISSUE TITLE
Problem with `summarise()`

### ISSUE THREAD

**Issue by Bithorax** [lpantano/DEGreport#37]
Hi,

Trying to run degPatterns but run into an error I cannot solve. When running: 

clusters<- degPatterns(cluster_rlog, metadata = meta, time = "Conc", col=NULL)

it throws the following error:

Working with 2832 genes.
Working with 2826 genes after filtering: minc > 15
Joining, by = "merge"
Error: Problem with `summarise()` input `n_genes`.
x could not find function "n"
ℹ Input `n_genes` is `n()`.
ℹ The error occured in group 1: merge = "one_group0", cluster = 1, Conc = "0", colored = "one_group".

I had the same errors when trying to use the example data provided here: https://rdrr.io/bioc/DEGreport/man/degPatterns.html. So I guess there is an issue with the function itself? 

Can someone help?

Thanks

**Comment by juanb001** [comment]
Any solutions to this? I'm getting the same error.

**Comment by lpantano** [comment]
Can you tell me the version of R and DEGreport you are using? I remember this was a problem in one of the R updates.

**Comment by juanb001** [comment]
Hi,

I'm using R 3.6.3 with DEGReport 1.22.0

Thanks!

**Comment by lpantano** [comment]
I think that is an old version issue. Any reason not to update to the current stable R version and bioc version?
