### ISSUE TITLE
Error in rep("one_group", nrow(metadata)) : invalid 'times' argument

### ISSUE THREAD

**Issue by elcega** [lpantano/DEGreport#39]
Does "times" need to be numeric or there is a minimum number of time groups? In my case I have 3 locations and they are characters. 

```
ma = assay(vsd)[row.names(res)[1:10],]
library(DEGreport)
res <- degPatterns(ma, design, time = "location")
```

> Error in rep("one_group", nrow(metadata)) : invalid 'times' argument

**Comment by lpantano** [comment]
Hi,

thank you for reporting the error. It doesn't need to be a number, and it can have mare than one.

Can you check `location` is a factor in design?

Can you let me know the package version?

Thanks!

**Comment by elcega** [comment]
Version is 1.24.1

How do I check if location is a factor in design? Do you mean as if it exists? 

This was run after:
```
dds <- DESeqDataSetFromMatrix(counts,
                                  colData = coldata,
                                  design=~location)
dds <- DESeq(dds)
```

**Comment by lpantano** [comment]
I am referring to this line:

res <- degPatterns(ma, design, time = "location")

I am assuming `design` is a data.frame, where row.names matches the col.names of matrix. I assume `location` is a column in design. You can check if it is a factor doing:

`design$location`, if it is a factor it would tell you at the end, showing on you the levels. To convert to a factor:

`design$location = as.factor(design$location)`

You can always save the environment after you run degPattern and get the error into a file and share the file somehow.

```
save.image(file = "my_work_space.RData")
```

Cheers.

**Comment by elcega** [comment]
I have this error: ```Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'as.factor': object of type 'closure' is not subsettable```

after running ```design$location = as.factor(design$location)```

**Comment by lpantano** [comment]
thank you,

with the enviroment you sent me I can do this:

```
res <- degPatterns(ma, metadata = colData(dds), time = "location", minc = 1)
```

design doesn't exists there, so you can get the metadata from the colData of the dds object. `minc` needs to be very low when you have few genes like 10. Ideally you want to run this when you have more than 50 genes or so.

Let me know if that line runs for you.

cheers

**Comment by elcega** [comment]
Yes, it actually worked! Fantastic, thanks I ran this:
```ma <- assays(vsd)[[1]][1:100,]
res <- degPatterns(ma, metadata = colData(dds), time = "location", minc = 5)```
I have more genes 1200 DEG of ~4000 but it does not let me run for bigger than that because I seem to have NAs? 
Error in diana(d, diss = TRUE, stand = FALSE) : NA values in the dissimilarity matrix not allowed.

- How can I remove the NAs from there, and also
-  is there a function where I can determine the number of groups I'd like? or it is automatic?

**Comment by lpantano** [comment]
Can you try to directly create the matrix with the 1200 DEG and try the command. That error could be because there are genes not expressed and the standard deviation is 0. Normally with real DEG that won’t happen. 

You would be able to select different cutoff. `res` will have benchmarking* figures that can help you see how different cutoff change the number of groups. Then you can user `res$normalized` and   http://lpantano.github.io/DEGreport/reference/degPlotCluster.html to choose what to plot or even select genes for whatever you want to do next.

Let me know how it goes.

**Comment by elcega** [comment]
Yes, it worked with the matrix, thanks!
```
res <- degPatterns(dfDEG, metadata = colData(dds), time = "location", minc = 5)
degPlotCluster(res$normalized, "location") ```
