### ISSUE TITLE
Extract the genes of each group pattern

### ISSUE THREAD

**Issue by elcega** [lpantano/DEGreport#41]
Can you extract as a data.frame a list of the genes included on each of the groups generated 
after ```degPlotCluster(res3$normalized, "condition")``` ?

**Comment by lpantano** [comment]
this function is only a proxy for plotting, so `res3$normalized` contains all the information you are seeing. Normally the column `cluster` has the group number you see in the plot, and you should have a column for genes, and the scaled expression as well. let me know if you don't find them.

**Comment by elcega** [comment]
Hey Lorena, yes, you are right, I see the cluster column. q) Just to confirm, is the "value" column defining which genes are most variable across x-axis "times"? Maybe is here but I have missed it https://bioconductor.org/packages/release/bioc/manuals/DEGreport/man/DEGreport.pdf

And so, from my understanding, the number of clusters is done based on a cut off (0.001-0.98) and a minimum number of genes per group. I have read you mentioned this cutoff can be defined in some kind of ```benchmarking``` function, but I have not seen any examples. Do you have any reproducible examples of using different cutoffs? I would like to try these different cut-offs to see how many groups and genes fall into these.

**Comment by lpantano** [comment]
closing this due to age, please open a new issue if this is still a question. Thanks!
