### ISSUE TITLE
lasso2 is an R4 only package

### ISSUE THREAD

**Issue by alpapan** [lpantano/DEGreport#43]
Currently DEGreport depends on lasso2 which is an R4 only package.

Can we have a version that is compatible with 3.6 (considering that R4 is quite broken... still...)

**Comment by lpantano** [comment]
Mmm, it is a good point, but normally the package install the version that
is compatible with the R version if you go with BiocManager.

How are you trying to installing?

For instance this is the last one for
https://bioconductor.org/packages/3.10/bioc/html/DEGreport.html.

If you are in 3.6 and using BiocManager, I can take a deeper look at this.
Maybe there is a glitch here.

Thanks
