### ISSUE TITLE
Show Expression Changes from One Cluster

### ISSUE THREAD

**Issue by drives28** [lpantano/DEGreport#45]
Hello,

I have the following design matrix (all columns are characters):  
                  group time replicate
ZN_D0_1  control    0         1
ZN_D0_2  control    0         2
ZN_D0_3  control    0         3
ZN_D1_1  control    1         1
ZN_D1_2  control    1         2
ZN_D3_1  control    3         1
ZN_D3_2  control    3         2
ZN_D3_3  control    3         3
ZN_D5_1  control    5         1
ZN_D5_2  control    5         2
ZN_D5_3  control    5         3
I23_D0_1     Trt1    0         1
I23_D0_2     Trt1   0         2
I23_D0_3    Trt1   0         3
I23_D1_1     Trt1   1         1
I23_D1_2     Trt1   1         2
I23_D1_3     Trt1    1         3
I23_D3_1     Trt1    3         1
I23_D3_2    Trt1    3         2
I23_D3_3    Trt1    3         3
I23_D5_1     Trt1    5         1
I23_D5_2     Trt1    5         2
I23_D5_3     Trt1    5         3
E33_D0_1     Trt2    0         1
E33_D0_2     Trt2    0         2
E33_D0_3     Trt2    0         3
E33_D1_1     Trt2    1         1
E33_D1_2     Trt2    1         2
E33_D1_3     Trt2    1         3
E33_D3_1     Trt2    3         1
E33_D3_2     Trt2    3         2
E33_D3_3     Trt2    3         3
E33_D5_1     Trt2    5         1
E33_D5_2     Trt2    5         2
E33_D5_3     Trt2    5         3

I have used DEGPatterns to obtain clusters for genes which show effects due to treatment (group) over time. I would like to show the boxplots for each group from a specific cluster over time. Similar to this individual's figure: https://github.com/lpantano/DEGreport/issues/35 

I thought there was an issue with my design matrix. I have tried having the time column as a numeric and as a character. I have also tried to merge according to the replicate column but to no avail. I have looked at the vignette for DEGreport, but I could have missed something. 

Any help would be appreciated, and I can provide more details if necessary.

**Comment by drives28** [comment]
If someone else is struggling with this,  @Ipantano had suggested the colData(dds) ['time'] should be a factor with issue #42. I changed my metadata columns to all be factors as opposed to characters and this fixed my issue. I now see all clusters of genes per group and the expression profile each cluster of genes exhibits over time. Hope this can help someone in the future.

**Comment by lpantano** [comment]
Thank you! Yes, that is the common issue. I will leave this open so people can see it quickly. Thanks again for the follow up.

**Comment by drives28** [comment]
No problem. Do you know if the metadata being factors/characters/numeric affects the DESeq2 output, or if this is specific to degPatterns? I used the same metadata for both and my previous analyses were a mix of characters and numerics. I'm wondering if I need to redo these analyses.

**Comment by lpantano** [comment]
No, it should be fine. DESeq2 will convert to factor, something I should do to be honest, but I always forget...

**Comment by drives28** [comment]
Thank you so much for your help and discussion!
