### ISSUE TITLE
Extract One Cluster Plot from degPlotCluster

### ISSUE THREAD

**Issue by drives28** [lpantano/DEGreport#46]
Hello again,

Is there a way to only output one cluster plot if the number of the cluster is used as input? Let me know if this question doesn't make sense. 

Thanks!

**Comment by lpantano** [comment]
Hi,

If you want to plot only one cluster, you can subset the data.frame containing only that cluster and then use the function. I have never tried that, let me know if that works. Or let me know if that wasn't the question :)

**Comment by drives28** [comment]
I had tried subsetting cluster_rlog prior to sending it to the degPatterns function but not subsetting the degPatterns output variable prior to inputting in degPlotCluster. I'll try that and let you know if it doesn't work. Thanks for your reply.

**Comment by drives28** [comment]
That did work. I output the genes for the cluster I'm interested in and then subset clusters1$normalized using the following code: group3cluster <- subset(clusters1$normalized, clusters1$normalized$genes %in% group3$genes)
then I can pass group3cluster to degPlotCluster and only output that one plot. 

Thanks so much!
