### ISSUE TITLE
Regarding Group # from degPatterns Output

### ISSUE THREAD

**Issue by drives28** [lpantano/DEGreport#51]
For reference, my experimental design is the same as in issue #45  

So I run the following code: 
clusters1 <- degPatterns(cluster_rlog, metadata = col_data, time = "time", col = "group", plot = TRUE, eachStep = TRUE, scale = TRUE)
clusters1$df
class(clusters1)

And I get all the clusters that have minc>15. I understand the clustering is based on DIANA. 

In the cluster output plot, the groups are listed as Group 1, Group 10, Group 11, Group 13, Group 14, Group 16, Group 17, Group 18, Group 19, Group 2, Group 20, Group 21............Group 3, Group 32......

My question is: Does the order of the output for the groups/clusters indicate the degree of variance (least similarity) from the mean for each group (treatment) (E.g. Group 1 is highest variance followed by Group 10, then Group 11, and so on)? OR is this just a matter of output based on reference number? (i.e. 1 comes before 2 and two digits follow a single digit)

Thank you so much in advance for your help!

Let me know if you need more details.

**Comment by drives28** [comment]
Or is the output similar to a dendrogram where the numbering indicates a relationship between clusters?

**Comment by lpantano** [comment]
Hi,

Thank you for the question, I don't think the number can be interpreted like that. The ordering of the clusters are not based on distance. I think there are packages that can do that, so I would need to add that to make sure the order makes sense.
