### ISSUE TITLE
Regarding Clustering Based on Expression Pattern

### ISSUE THREAD

**Issue by drives28** [lpantano/DEGreport#52]
Hello,

I have cluster outputs from degPatterns where you can tell the expression pattern is the same/similar across sample groups. So this makes sense based on how the clustering is performed. 

However, I have some from the output where they may be similar up until my last timepoint, for example. And then I have some groups where I see a different pattern of expression between sample groups. How can this be?

You wrote in issue #28 "It is normal to find clusters that go almost identical, but you can see there is always a little different. I use the plot to then merge the groups to make more sense with your biology. If that little difference is not important, it makes sense to put all together."  

I don't understand what you mean by the above sentence. I have a plot showing the normalized value across groups and time. Code:
p <- ggplot(clusters1[["normalized"]], aes(time, value, color=group, fill=group)) +
    geom_boxplot() + 
    theme_classic() +
    scale_fill_manual(values=c('darkgray', 'darkorange2', 'darkorchid4')) +
    scale_colour_manual(values=c('black', 'black', 'black'))
p

But this is a single plot, and I'm not sure how that would help me understand the biology going on in one of my generated clusters, unless it is showing there are more DEGs at a particular timepoint and so that timepoint may perturb the expression pattern in a given cluster from the degPatterns output. Is this what you mean?

If not, I'm not sure how I would merge the groups for a single cluster? 

Thanks in advance for your help!

Let me know if you need more details.

**Comment by lpantano** [comment]
Hi,

It is indeed a complex discussion. Without knowing your groups for your example I don't know if I would be able to help a lot. 

I had one study that was disease across stages, being 0 the less aggressive state and 4 the most.  When I did the clustering I had a bunch of groups that were all going UP across stages, with a little difference on saturating at 3 or 4. I did enrichment analysis for each of the group and I figured that those groups belonged to the same pathways, so I decided to merge it.

I would say you are looking for the biggest difference among your groups. 

I hope this helps.
