### ISSUE TITLE
`lasso2` dependency no longer on CRAN

### ISSUE THREAD

**Issue by kennyworkman** [lpantano/DEGreport#53]
heads up `lasso2` is no longer archived

currently have to install from source manually - https://cran.r-project.org/src/contrib/Archive/lasso2/

**Comment by mjsteinbaugh** [comment]
+1 I'm hitting warnings for this when installing bcbioRNASeq

**Comment by mjsteinbaugh** [comment]
Awesome thanks Lorena!

**Comment by lpantano** [comment]
ok, this should be fixed in bioc 3.16 that is about to be released in the next weeks.you can try installing from main branch here and see if you get rid of the error.

**Comment by mjsteinbaugh** [comment]
Thanks @lpantano ! Hope you're doing well
