### ISSUE TITLE
Boxplot position

### ISSUE THREAD

**Issue by Chunhuixu** [lpantano/DEGreport#55]
Hi there,
Firstly, thanks for developing this wonderful tool to visualize trends.
I'm wondering if the function can re-position the boxplot in the same line(the blue line in the graph) instead of in the two wings of blue line. 
![box](https://user-images.githubusercontent.com/11236354/207433400-d91cb37e-8681-44c7-b16a-6b72143cca30.png)

Thanks for the help!

Chunhui

**Comment by lpantano** [comment]
Hi,

I don't know how to do that, but you get the data used to make this plot from the function, so maybe you find a way to change that position. By default it is not in the same place in case there is an overlap. 

sorry I cannot help more.
