### ISSUE TITLE
issues with  degPatterns not setting Time in Normalize

### ISSUE THREAD

**Issue by kesner** [lpantano/DEGreport#57]
First my versions: OSX latest R version:
[1] dplyr_1.1.1                 tibble_3.2.1                plyr_1.8.8                 
 [4] cluster_2.1.4               edgeR_3.40.2                limma_3.54.2               
 [7] DEGreport_1.34.0            pheatmap_1.0.12             ggplot2_3.4.2              
[10] DESeq2_1.38.3               SummarizedExperiment_1.28.0 Biobase_2.58.0             
[13] MatrixGenerics_1.10.0       matrixStats_0.63.0          GenomicRanges_1.50.2       
[16] GenomeInfoDb_1.34.9         IRanges_2.32.0              S4Vectors_0.36.2           
[19] BiocGenerics_0.44.0 

I do not see Time being set in the structure returned from degPatterns.

metadata:  Exp Time (integer 0,1,2) Treat (levels WT KO with WT being default)

clusters_rlog_padj<- degPatterns(cluster_rlog_padj, metadata = metadata, time="Time", col="Treat", minc=0)

In  clusters_rlog_padj I see time set in raw but in normalized.  To get degPlotCluster(clusters_rlog_padj\$normalized, time="Time", color="Treat",min_genes=0) to work I first have to run clusters_rlog_padj\$normalized\$Time<-clusters_rlog_padj\$raw\$Time
I see this with View in Rstudio of the returned clusters_rlog_padj.  Without doing this, normalized>Time has Type factor with values Factor with 0 levels. "".   Even though Time is not set up as a factor but an integer taking the values 0 1 or 2.

As an aside I also see normalized>merge to be 'WT0' 'WT0' 'WT0' ....  Where as in raw, merged is 'KO0' 'KO0' 'KO0' ...
Is this correct, should normalized had raw have the same merge order since time in Raw seems to be correct  independent
of merged.

OTHER INFO:

metadata is 
Exp	Time	Treat
s1	0	WT
s2	0	WT
s3	0	WT
s4	1	WT
s5	1	WT
s6	1	WT
s7	2	WT
s8	2	WT
s9	2	WT
s10	0	KO
s11	0	KO
s12	0	KO
s13	1	KO
s14	1	KO
s15	1	KO
s16	2	KO
s17	2	KO
s18	2	KO

Model using is : reduced: Treat + Time
                            full.          Treat + Time + Treat:Time

Let me know what else you need?

**Comment by lpantano** [comment]
Hi,

Can you check Time column is a factor?

**Comment by lpantano** [comment]
As well, if you could save the object and send it to me, I could try to troubleshoot more.Thanks.

**Comment by kesner** [comment]
Hi,
  My Time is an integer in the raw version.  In the normalized version it
say it is a factor.  I am doing time series analysis and want to use Time
as part of the linear regression model as I thought your code is doing.
Barry

**Comment by kesner** [comment]
Hi,

  Here is my code and data.

Barry

**Comment by kesner** [comment]
Hi,
  Metadata,save needs to me stored as just metadata for the code to work.
Barry

**Comment by kesner** [comment]
Another question.
 Do you know how to label the genes on the degPlotCluster plots?
Barry

**Comment by lpantano** [comment]
Hi, I think you would need some ggplot code for that. Probably adding with geom_text or with ggrepel, if you don't have many it may work.

**Comment by kesner** [comment]
Thanks,
  Yes ilI did!
Barry
