### ISSUE TITLE
`scale` parameter is missing in `degPCA`

### ISSUE THREAD

**Issue by bounlu** [lpantano/DEGreport#63]
There is no parameter in `degPCA` to pass `scale` to `prcomp` function, which means the data is not scaled during PCA. However, scaling the data before PCA is often suggested.

**Comment by lpantano** [comment]
Hi,

Scaled in what dimension? I could add the parameter but we want to leave to the bioinformatician the right input to use, because it would vary across different data sets. What is your normal case?
